### ISSUE TITLE
cookie  result is empty

### ISSUE THREAD

**Issue by MuratGOZCU** [nemi-chand/CookieManager#3]
I've tried operations one-to-one,

_cookie.Set ("Key", "value here", 10);
string keystr = _cookie.Get ("Key"); // result empty is coming.

with the order of transactions,
nuget package download,
Including Icookiemanager and Icookie from the project
then middleware
services.addcookiemanag is ();
I added the code.
but the value is empty.

**Comment by nemi-chand** [comment]
@MuratGOZCU Thanks for using Cookie Manager. it is an expected behavior of http Cookie. When you are setting cookie a browser append in to response header, It will send all the cookie associated with domain along the request. In the first ever call there will be no cookies. Only after the response is returned from your method it will have a Cookie. From the second requests onwards, when you refresh or send a second request , the cookies returned from the first call will be present in the second call. Hence in second request "string keystr = _cookie.Get ("Key");" will have value.

Still you want value from cookie while setting then use the **ICookieManager.GetOrSet()** Method. this is return the same value you are setting

```
Object myCook = _cookieManager.GetOrSet<Object>("Key", () =>
     {
	//write fucntion to store  output in cookie
	  return new Object()
	   {
	         Id = Guid.NewGuid().ToString(),
		 Indentifier = "valueasgrsdgdf66514sdfgsd51d65s31g5dsg1rs5dg",
		  Date = DateTime.Now
	  };
     }, 60);
```
Hope it helps.

**Comment by MuratGOZCU** [comment]
thanks. cookie did not occur because the page was not refreshed. I have experienced this problem because I use angular.
